# Generated by Django 4.2.13 on 2026-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_grind_orderitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='grind',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
