# Generated by Django 4.2.13 on 2024-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('coffee_beans', 'Coffee Beans'), ('canned_coffee', 'Canned Coffee'), ('brewing_equipment', 'Brewing Equipment')], max_length=20)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
